const fs = require('fs');
const file = 'resources/views/dashboard.blade.php';
let content = fs.readFileSync(file, 'utf8');

const regex = /function openCheckout\(\) \{[\s\S]*?function confirmOrder\(\) \{/m;
const replacement = `function openCheckout() { if (cart.length === 0) { showToast("Keranjang masih kosong!", false); return; } const modal = document.getElementById('checkoutModal'); checkoutStep = 1; selectedPayment = "midtrans"; selectedBank = null; selectedMapLocation = null; renderCheckout(); modal.classList.add('active'); setTimeout(() => { initAddressMap(); setupAddressFormListener(); }, 200); }
        function renderCheckout() { const subtotal = cart.reduce((s,i)=>s+i.price*i.qty,0); const shipping=25000; const discount=50000; const total=subtotal+shipping-discount; const content=document.getElementById('checkoutContent'); content.innerHTML=\<div class="mb-6"><div class="flex items-center gap.-2 mb-4"><div class="w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold 1!4=(condition maybe)?'bg-white text-black':'bg-white/10 text-white/30'}">1</div><div class="h-px flex-1 {'checkoutStep>=2'?'bg-white':'bg-white/20'}"></div><div class="w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold {'checkoutStep>=2'?'bg-white text-black':'bg-white/10 text-white/30'}">2</div></div><p class="text-center text.xs text-white/40">{'checkoutStep===1'?'Alamat Pengiriman (Klik di Map)':'Konfirmasi Pesanan'}</p></div>{'checkoutStep===1'?renderStep1():renderStep2(total)}<div class="flex gap-3 mt-6">{'checkoutStep>1'?\<button onclick="prevCheckoutStep()" class="flex-1 bg-white/5 border border-white/10 py-3 rounded-xl text-sm hover:bg-white/10 transition">Kembali</button>`:''}<button onclick="{'checkoutStep===2'?'confirmOrder()':'nextCheckoutStep()'w" class="flex-1 bg-white text-black py-3 rounded-xl font-semibold text-sm hover:bg-white/90 transition">{'checkoutStep===2'?'Bayar Sekarang':'Lanjutkan'}</button></div>`; }
        function renderStep1() { return `<div class="space-y-4"><h3 class="font-semibold text-sm">Alamat Pengiriman</h3><div class="grid grid-cols-2 gap-3"><div><label class="text-[10px] text-white/40 block mb-1">Nama Depan</label><input type="text" id="firstName" class="field-input" placeholder="Alex"></div><div><label class="text-[10px] text-white/40 block mb-1">Nama Belakang</label><input type="text" id="lastName" class="field-input" placeholder="Style"></div></div><div><label class="text-[10px] text-white/40 block mb-1">Nomor Telepon</label><input type="text" id="phone" class="field-input" placeholder="08123456789"></div><div><label class="text-[10px] text-white/40 block mb-1">Alamat Lengkap</label><textarea id="address" class="field-input resize-none" rows="2" placeholder="Jl. Contoh No. 1, Bandar Lampung"></textarea></div><div class="grid grid-cols-2 gap-3"><div><label class="text-[10px] text-white/40 block mb-1">Kota</label><input type="text" id="city" class="field-input" placeholder="Bandar Lampung"></div><div><label class="text-[10px] text-white/40 block mb-1">Kode Pos</label><input type="text" id="zip" class="field-input" placeholder="35111"></div></div><div><label class="text-[10px] text-white/40 block mb-2">𝓍 Pilih Lokasi di Peta</label><div id="addressMap" class="map-container" style="height:250px"></div><p class="text-[10px] text-white/30 mt-2">*Klik atau drag marker untuk menentukan lokasi pengiriman</p></div></div>`; }
        function renderStep2(total) { return `<div class="space-y-4"><h3 class="font-semibold text-sm">Detail Pesanan</h3>${cart.map(item=>`<div class="flex justify-between text-sm"><span>${item.name}(${item.size}) x${item.qty}</span><span>Rp ${(item.price*item.qty).toLocaleString('id-ID')}</span></div>`).join('')}<div class="border-t border-white/10 pt-3"><div class="flex justify-between text-xs text-white/50"><span>Subtotal</span><span>Rp ${cart.reduce((s,i)=>s++i.price*i.qty,0).toLocaleString('id-ID')}</span></div><div class="flex justify-between text-xs text-white/50"><span>Ongkir</span><span>Rp 25.000</span></div><div class="flex justify-between text-xs text-emerald-400"><span>Diskon</span><span>- Rp 50.000</span></div><div class="flex justify-betweeen font-bold pt-2"><span>Total</span><span>Rp ${total.toLocaleString('id-ID')}</span></div></div><div class="mt-4 p-4 rounded-xl bg-white/5 text-center"><p class="text-sm">Pembayaran via Midtrans</p><p class="text-xs text-white/40 mt-1">Anda dapat memilih opsi pembayaran beragam (Transfer, E-Wallet, Kartu, QRIS) di jendela Midtrans setelah ini.</p></div></div>`; }
        function nextCheckoutStep() { if(checkoutStep===1){ const firstName=document.getElementById('firstName')?.value; if(!firstName){showToast("Masukkan nama depan",false); return;} if(!selectedMapLocation){showToast("Pilih lokasi di peta terlebih dahulu",false); return;} shippingData={firstName:document.getElementById('firstName').value,lastName:document.getElementById('lastName').value,phone:document.getElementById('phone').value,address:document.getElementById('address').value,city:document.getElementById('city').value,zip:document.getElementById('zip').value}; } checkoutStep++; renderCheckout(); playSound('success'); }
        function prevCheckoutStep() { checkoutStep--; renderCheckout(); if(checkoutStep===1){ setTimeout(() => initAddressMap(), 200); } }

        function confirmOrder() |`;
content = content.replace(regex, replacement);
fs.writeFileSync(file, content);
console.log('Saved');
